name: Request Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Generate .alf file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Unity Activation File
        uses: game-ci/unity-activate@v2
        id: getLicense
        with:
          unityVersion: 2021.3.29f1   # replace with your Unity version
          activationMode: request

      - name: Upload .alf file
        uses: actions/upload-artifact@v3
        with:
          name: Unity-Activation-File
          path: ${{ steps.getLicense.outputs.alfFilePath }}
