name: Build Unity Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip Unity Project
        run: |
          mkdir project
          unzip -q Exorcist_Full_Unity_2021_Project.zip -d project
          ls project

      - name: Build Android Player
        uses: game-ci/unity-builder@v2
        with:
          projectPath: project
          unityVersion: 2021.3.20f1
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/Android/*.apk
